// <auto-generated />
using System;
using CapShop.CatalogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapShop.CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gadgets & devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fashion & apparel",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books & magazines",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home essentials",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sports & fitness",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Beauty & personal care",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Toys & games",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Home furniture",
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest Apple smartphone",
                            ImageUrl = "https://images.unsplash.com/photo-1696446702183-a03dff5b2f1f?w=400",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apple M3 Pro chip laptop",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
                            IsActive = true,
                            Name = "MacBook Pro 14",
                            Price = 1999.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium noise cancelling headphones",
                            ImageUrl = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400",
                            IsActive = true,
                            Name = "Sony WH-1000XM5",
                            Price = 349.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced smartwatch",
                            ImageUrl = "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400",
                            IsActive = true,
                            Name = "Apple Watch Series 9",
                            Price = 399.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional Apple tablet",
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
                            IsActive = true,
                            Name = "iPad Pro 12.8",
                            Price = 1099.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton premium quality",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
                            IsActive = true,
                            Name = "Classic White T-Shirt",
                            Price = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable stretch denim",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
                            IsActive = true,
                            Name = "Slim Fit Jeans",
                            Price = 59.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather biker jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
                            IsActive = true,
                            Name = "Leather Jacket",
                            Price = 199.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight performance shoes",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
                            IsActive = true,
                            Name = "Running Shoes Nike",
                            Price = 89.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CategoryName = "Clothing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable fleece hoodie",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400",
                            IsActive = true,
                            Name = "Hoodie Pullover",
                            Price = 44.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CategoryName = "Books",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agile software craftsmanship by Robert C. Martin",
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 39.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CategoryName = "Books",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tiny changes remarkable results",
                            ImageUrl = "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
                            IsActive = true,
                            Name = "Atomic Habits",
                            Price = 24.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CategoryName = "Books",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Paulo Coelho's magical novel",
                            ImageUrl = "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400",
                            IsActive = true,
                            Name = "The Alchemist",
                            Price = 15.99m,
                            Stock = 160
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CategoryName = "Books",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands-on introduction to programming",
                            ImageUrl = "https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=400",
                            IsActive = true,
                            Name = "Python Crash Course",
                            Price = 39.99m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CategoryName = "Books",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "What the rich teach about money",
                            ImageUrl = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
                            IsActive = true,
                            Name = "Rich Dad Poor Dad",
                            Price = 19.99m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "7-in-1 electric pressure cooker",
                            ImageUrl = "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
                            IsActive = true,
                            Name = "Instant Pot Duo",
                            Price = 89.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automatic espresso coffee maker",
                            ImageUrl = "https://images.unsplash.com/photo-1570486829-82b5494d2d4b?w=400",
                            IsActive = true,
                            Name = "Nespresso Machine",
                            Price = 149.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stand mixer for baking",
                            ImageUrl = "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
                            IsActive = true,
                            Name = "KitchenAid Mixer",
                            Price = 299.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HEPA filter air purifier",
                            ImageUrl = "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400",
                            IsActive = true,
                            Name = "Air Purifier",
                            Price = 199.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1000 thread count Egyptian cotton",
                            ImageUrl = "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400",
                            IsActive = true,
                            Name = "Bed Sheet Set",
                            Price = 79.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CategoryName = "Sports",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip exercise yoga mat",
                            ImageUrl = "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400",
                            IsActive = true,
                            Name = "Yoga Mat Premium",
                            Price = 49.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CategoryName = "Sports",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable weight dumbbell set",
                            ImageUrl = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
                            IsActive = true,
                            Name = "Dumbbell Set",
                            Price = 129.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CategoryName = "Sports",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight road cycling helmet",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
                            IsActive = true,
                            Name = "Cycling Helmet",
                            Price = 79.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CategoryName = "Sports",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional grade tennis racket",
                            ImageUrl = "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
                            IsActive = true,
                            Name = "Tennis Racket",
                            Price = 89.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CategoryName = "Sports",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Whey protein chocolate flavor 2kg",
                            ImageUrl = "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400",
                            IsActive = true,
                            Name = "Protein Powder",
                            Price = 59.99m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            CategoryName = "Beauty",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Brightening face serum 30ml",
                            ImageUrl = "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
                            IsActive = true,
                            Name = "Vitamin C Serum",
                            Price = 34.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            CategoryName = "Beauty",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supersonic professional hair dryer",
                            ImageUrl = "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400",
                            IsActive = true,
                            Name = "Hair Dryer Dyson",
                            Price = 429.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            CategoryName = "Beauty",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily moisturizer with sun protection",
                            ImageUrl = "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
                            IsActive = true,
                            Name = "Moisturizer SPF50",
                            Price = 29.99m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CategoryName = "Beauty",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxury fragrance gift set",
                            ImageUrl = "https://images.unsplash.com/photo-1541643600914-78b084683702?w=400",
                            IsActive = true,
                            Name = "Perfume Set",
                            Price = 89.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            CategoryName = "Beauty",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oral-B smart electric toothbrush",
                            ImageUrl = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400",
                            IsActive = true,
                            Name = "Electric Toothbrush",
                            Price = 69.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            CategoryName = "Toys",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced building block set 1500pcs",
                            ImageUrl = "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
                            IsActive = true,
                            Name = "LEGO Technic Set",
                            Price = 99.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            CategoryName = "Toys",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High speed RC car 1:10 scale",
                            ImageUrl = "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400",
                            IsActive = true,
                            Name = "Remote Control Car",
                            Price = 79.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            CategoryName = "Toys",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic family board game",
                            ImageUrl = "https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?w=400",
                            IsActive = true,
                            Name = "Board Game Monopoly",
                            Price = 34.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            CategoryName = "Toys",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Beginner friendly mini drone",
                            ImageUrl = "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400",
                            IsActive = true,
                            Name = "Drone Mini",
                            Price = 49.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            CategoryName = "Toys",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scenic landscape jigsaw puzzle",
                            ImageUrl = "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
                            IsActive = true,
                            Name = "Puzzle 1000pcs",
                            Price = 24.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            CategoryName = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic mesh office chair",
                            ImageUrl = "https://images.unsplash.com/photo-1596162954151-cdcb4c0f70a8?w=400",
                            IsActive = true,
                            Name = "Office Chair",
                            Price = 299.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            CategoryName = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Height adjustable standing desk",
                            ImageUrl = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400",
                            IsActive = true,
                            Name = "Standing Desk",
                            Price = 499.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            CategoryName = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern wooden bookshelf",
                            ImageUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
                            IsActive = true,
                            Name = "Bookshelf 5 Tier",
                            Price = 149.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            CategoryName = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern fabric 3-seater sofa",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
                            IsActive = true,
                            Name = "Sofa 3-Seater",
                            Price = 799.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 8,
                            CategoryName = "Furniture",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Solid wood queen size bed frame",
                            ImageUrl = "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=400",
                            IsActive = true,
                            Name = "Bed Frame Queen",
                            Price = 599.99m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("CapShop.CatalogService.Domain.Entities.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapShop.CatalogService.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
